SELECT * FROM POSTAGEM WHERE ID_USUARIO <> 1;
SELECT * FROM POSTAGEM WHERE ID_USUARIO <> 2;
SELECT * FROM POSTAGEM WHERE ID_USUARIO <> 3;

SELECT COMENTARIO.MENSAGEM,USUARIO.NOME FROM COMENTARIO, USUARIO WHERE COMENTARIO.ID_USUARIO = USUARIO.ID AND ID_POSTAGEM = 1;
SELECT COMENTARIO.MENSAGEM,USUARIO.NOME FROM COMENTARIO, USUARIO WHERE COMENTARIO.ID_USUARIO = USUARIO.ID AND ID_POSTAGEM = 2;
SELECT COMENTARIO.MENSAGEM,USUARIO.NOME FROM COMENTARIO, USUARIO WHERE COMENTARIO.ID_USUARIO = USUARIO.ID AND ID_POSTAGEM = 3;


SELECT REACAO.DESCRICAO, USUARIO.NOME FROM POSTAGEM, REACAO, REACAO_POSTAGEM, REACAO_USUARIO, USUARIO WHERE USUARIO.ID = REACAO_USUARIO.ID_USUARIO
AND REACAO.ID = REACAO_USUARIO.ID_REACAO AND POSTAGEM.ID = REACAO_POSTAGEM.ID_POSTAGEM AND REACAO_USUARIO.ID = REACAO_POSTAGEM.ID_REACAO_USUARIO AND POSTAGEM.ID = 2; 
